os:
  - linux

dist: bionic

language: python
python:
  - 3.7


before_script:
  - python -V

jobs:
  include:
    - stage: Linting
      script:
        - pip install -r requirements.txt
        - pip install flake8
        - flake8 $(find norminette/ -d -name "*.py")
   - stage: Unit tests
     script:
       - cd norminette && python -m unittest discover tests/lexer/unit-tests "*.py"
   - stage: Lexer tests
     script:
       - python -m tests.lexer.files.file_token_test
       - python -m tests.lexer.errors.tester
   - stage: Rule tests
     script:
       - python -m tests.rules.rule_tester
